# Use an existing docker image as a base
FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./

# download and install a depdendancies
RUN npm install



#Tell the image what to do when it starts as a contianer
COPY ./ ./
CMD ["npm","run","start"]
